version: "3"

networks:
  sao-network:

services:
  routeros-6-44:
    image: evilfreelancer/docker-routeros:6.46.5
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "22222:22"
      - "22223:23"
      - "28728:8728"
      - "28729:8729"
    networks:
      - sao-network
      
  client:
    image: ubuntu:20.04
    networks:
      - sao-network
